name: Daily Test Automation

on: push 

jobs:
  cypress-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout Web Repository
        uses: actions/checkout@v2
        with:
          repository: missionpeakus/mission-peak-e2e-tests  # Replace with the owner and name of the web repository
          path: master
          token: ${{ github.token }} 
          ref: main
    
         
          
      - name: Install Dependencies for Web Repository
        run: npm install
        working-directory: master # Switch to the directory of the web repository

      - name: Run Cypress Tests
        run: npm run cypress:run -- --browser chrome   # Adjust the Cypress command based on your configuration
